name: rush_prompt
description: A library for creating CLI prompts.
version: 0.0.1+10
authors:
  - 'Shreyash Saitwal'
environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  dart_console: ^0.6.2
