name: rush_prompt
description: A library for creating CLI prompts.
version: 0.0.1+10

authors:
  - 'Shreyash Saitwal'

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

dependencies:
  dart_console: ^1.0.0
