include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - always_put_required_named_parameters_first
    - sort_pub_dependencies
    - avoid_empty_else
    - avoid_relative_lib_imports
    - prefer_single_quotes

analyzer:
  enable-experiment:
    - non-nullable
