name: rush_cli
description: A simple CLI to quickly scaffold App Inventor extensions.
version: 0.0.1+1
homepage: https://github.com/ShreyashSaitwal/rush-cli

executables:
  rush: rush.dart

authors:
  - Shreyash Saitwal

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

dependencies:
  rush_prompt:
    path: packages/rush_prompt
  args: ^1.6.0
  dart_console: ^0.6.2
  hive: ^1.4.4+1
  meta: ^1.2.4
  path: ^1.7.0
  yaml: ^2.2.1
